[workspace]
default-members = ["conduit"]
members = ["conduit", "conduit-config", "conduit-macros", "xtask"]
resolver = "2"

[workspace.lints.rust]
explicit_outlives_requirements = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
cloned_instead_of_copied = "warn"
dbg_macro = "warn"
str_to_string = "warn"

[workspace.package]
# See also `rust-toolchain.toml`
edition = "2024"
homepage = "https://conduit.rs"
repository = "https://gitlab.com/famedly/conduit"
rust-version = "1.88.0"

[workspace.dependencies]
bytesize = "2"
# Removing the `color` feature as it is not used in the admin room commands.
# `string` feature is added for some reason, not sure.
# Added `derive` feature to allow derive macros
clap = { version = "4", default-features = false, features = [
  "derive",
  "error-context",
  "help",
  "std",
  "string",
  "usage",
] }
conduit-config.path = "conduit-config"
conduit-macros.path = "conduit-macros"
reqwest = { version = "0.12", default-features = false }
ruma.git = "https://github.com/ruma/ruma.git"
rusty-s3 = "0.8"
serde = "1"
serde_json = "1"
thiserror = "2"

[profile.dev]
incremental = true
lto = 'off'

[profile.release]
codegen-units = 32
incremental = true
lto = 'thin'
# If you want to make flamegraphs, enable debug info:
# debug = true

# For releases also try to max optimizations for dependencies:
[profile.release.build-override]
opt-level = 3
[profile.release.package."*"]
opt-level = 3
