[package]
edition.workspace = true
homepage.workspace = true
name = "conduit-macros"
repository.workspace = true
rust-version.workspace = true
version = "0.11.0-alpha"

[lib]
proc-macro = true

[dependencies]
# Parsing and quoting tokens
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[features]
default = ["doc-generators"]
doc-generators = []

[lints]
workspace = true
